/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.jmirazors.jmiСalculator.jmiframes;

import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import ru.jmirazors.jmiСalculator.DAO.LogDAO;
import ru.jmirazors.jmiСalculator.entity.Log;

/**
 *
 * @author User
 */
public class JournalDialog extends javax.swing.JDialog {

    /**
     * Creates new form JournalDialog
     */
    DefaultTableModel tableModel = new DefaultTableModel();
    public JournalDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        tableModel.addColumn("№");
        tableModel.addColumn("Пользователь");
        tableModel.addColumn("Время");
        tableModel.addColumn("Событие");
        initComponents();
        
        
        getJournal();
    }
    
    void getJournal(){
        for (int i=tableModel.getRowCount(); i > 0; i--) {
            tableModel.  removeRow(i-1);
        }  
        tableModel.setRowCount(0);
        
        try {
            List offers = new LogDAO().list();
            Iterator it = offers.iterator();
            while (it.hasNext()) {
                Log log = (Log)it.next(); 
                tableModel.addRow(new Object[]{log.getId(), log.getUser().getName(),
                log.getIndate(), log.getJob()});                
            }
        } catch (Exception e) {System.out.print(e);} 
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Журнал событий");
        setIconImage(null);

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
