/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.jmirazors.jmiСalculator.jmiframes;

import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import ru.jmirazors.jmiCalculator.beans.DocumentUtil;
import ru.jmirazors.jmiСalculator.DAO.DocumentDAO;
import ru.jmirazors.jmiСalculator.DAO.SubordinDAO;
import ru.jmirazors.jmiСalculator.jmiframes.Documents.Document;
import ru.jmirazors.jmiСalculator.entity.Subordin;

/**
 *
 * @author User
 */
public class SubordinDocDialog extends javax.swing.JDialog {

    /**
     * Creates new form SubordinDocDialog
     */
    
    DefaultTableModel tableModel = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int col) {
                return false; 
        }
            
    };
    DocumentDAO documentDAO;
    SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy HH:mm");
    
    public SubordinDocDialog(java.awt.Frame parent, boolean modal, List<Subordin> documents) {
        super(parent, modal);
        initComponents();
        tableModel.addColumn("L1");
        tableModel.addColumn("L2");
        tableModel.addColumn("Документ");
        tableModel.addColumn("№");
        tableModel.addColumn("дата");
        tableModel.addColumn("Пользователь");        
        tableModel.addColumn("Статус");
        jTable1.getColumnModel().getColumn(0).setMaxWidth(16);
        jTable1.getColumnModel().getColumn(0).setMinWidth(16);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(16);
        jTable1.getColumnModel().getColumn(1).setMinWidth(16);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(140);
        jTable1.getColumnModel().getColumn(2).setMinWidth(140);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(36);
        jTable1.getColumnModel().getColumn(3).setMinWidth(36);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(96);
        jTable1.getColumnModel().getColumn(4).setMinWidth(96);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(160);
        jTable1.getColumnModel().getColumn(5).setMinWidth(160);

        
        
//        tableModel.addColumn("Со скидкой");
//        tableModel.addColumn("Сумма"); 
        documentDAO = new DocumentDAO();
        Document doc = null;
        List<Subordin> subdocs_l2;
        for (Subordin sd: documents) {
            try {
                doc = documentDAO.getDocument(""+sd.getSub_id(),            
                        new DocumentUtil().getDocumentClass(sd.getSubdoc_id()));
                System.out.println(doc);
                tableModel.addRow(new Object[]{"-", "", doc.getDocuments().getName(), doc.getId(), format.format(doc.getIndate()), 
                    doc.getUsr().getName(), doc.getStatus().getName()});
                subdocs_l2 = new SubordinDAO().list(doc.getId(), doc.getDocuments().getId());
            for (Subordin sd2: subdocs_l2) {
                doc = documentDAO.getDocument(""+sd2.getSub_id(), 
                        new DocumentUtil().getDocumentClass(sd2.getSubdoc_id())); 
                tableModel.addRow(new Object[]{"", "--", doc.getDocuments().getName(), doc.getId(), format.format(doc.getIndate()), 
                    doc.getUsr().getName(), doc.getStatus().getName()});
            }                
            } catch (Exception ex) {
                Logger.getLogger(SubordinDocDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Подчиненные документы");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(640, 240));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        jButton1.setText("Закрыть");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
